# Generated by Django 4.0 on 2022-03-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidDevices',
            fields=[
                ('appid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('deviceid', models.CharField(max_length=64)),
                ('devicename', models.CharField(blank=True, max_length=64, null=True)),
                ('deviceversion', models.CharField(blank=True, max_length=64, null=True)),
                ('devicemodel', models.CharField(blank=True, max_length=64, null=True)),
                ('deviceserial', models.CharField(blank=True, max_length=64, null=True)),
                ('remoteuser', models.CharField(blank=True, max_length=255, null=True)),
                ('remoteaddr', models.CharField(blank=True, max_length=255, null=True)),
                ('useragent', models.CharField(blank=True, max_length=255, null=True)),
                ('registrationid', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ANDROIDDEVICES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NspRoutes',
            fields=[
                ('routeid', models.FloatField(primary_key=True, serialize=False)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.FloatField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.FloatField(blank=True, null=True)),
                ('technicianid', models.FloatField(blank=True, null=True)),
                ('routedate', models.DateField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('socount', models.FloatField(blank=True, null=True)),
                ('solist', models.CharField(blank=True, max_length=300, null=True)),
                ('polylinepoints', models.CharField(blank=True, max_length=4000, null=True)),
                ('googlejson', models.TextField(blank=True, null=True)),
                ('warehouseid', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'NSPROUTES',
                'managed': False,
            },
        ),
    ]
