# Generated by Django 4.0 on 2022-03-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NspPickingBatches',
            fields=[
                ('batchid', models.FloatField(primary_key=True, serialize=False)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.FloatField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.FloatField(blank=True, null=True)),
                ('warehouseid', models.CharField(blank=True, max_length=15, null=True)),
                ('ticketcount', models.FloatField(blank=True, null=True)),
                ('partcount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NSPPICKINGBATCHES',
                'managed': False,
            },
        ),
    ]
