"""
Django settings for kw_django project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cad^=4*ep4@fno1jg21*4=)-9vgtm)73w&*2b++ks5#zlmr^n-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'functions',
    'nsp_user',
    'tech_summary',
    'schedules_list_map',
    'schedules_detail',
    'repair_tasks',
    'picking_tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kw_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kw_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'orcl',
        'USER': 'dbuser',
        'PASSWORD': 'dbuser',
        'HOST': 'localhost',
        'PORT': '1521',
    },
    'docdb': {  #for connection to the DB tables PICTURES, DOCFILES, DOCFOLDERS, DOCNODES
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'orcl',
        'USER': 'dbuser',
        'PASSWORD': 'onlydbuser',
        'HOST': 'localhost',
        'PORT': '1522',
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

USE_TZ = False

USE_L10N = True

DATE_FORMAT = "Y-m-d"



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#URLs used to post XML data
DEV_ENDPOINT_URL = 'http://devoffice.kwinternational.com/nsp/ws/nsp4mobile.asmx'
PROD_ENDPOINT_URL = 'http://office.kwinternational.com/nsp/ws/nsp4mobile.asmx'

#URLs used in GSPN samsung service
DEV_GSPN = 'https://www.samsungasc.com/nawss/soap/sGSPNdev?wsdl'
PROD_GSPN = 'https://www.samsungasc.com/nawss/soap/sGSPN?wsdl'

#GSPNWSClient constants
GSPN_COMPANY = "C310"
GSPN_ASC_NAME = "KWI"
GSPN_WS_USER_ID = "KWI"
GSPN_WS_PASSWORD = "KWI1234PASS"
GSPN_ASC_NO_KWINT = "4273282"
GSPN_ASC_NO_KWLF = "4300930"
GSPN_CODE_TYPE_DEFECT = "EIA-D"
GSPN_CODE_TYPE_REPAIR = "EIA-R"

#SMTP GATEWAY DETAILS
EMAIL_HOST = '127.0.0.1'
EMAIL_PORT = 25
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
FROM_ADDRESS = 'KW Services API <admin@kwitech.com>'
TO_ADDRESS = 'developer_nsp@kwitech.com'

#NSC_LOG EMAIL ADDRESSES
NSP_INFO_EMAIL = 'developer_nsp@kwitech.com'
NSC_ADMIN_EMAIL = 'developer_nsp@kwitech.com'
DEVNSP_INFO_EMAIL = 'developer_nsp@kwitech.com'
NSC_ADMIN_EMAIL_DEV = 'developer_nsp@kwitech.com'
STM_INFO_EMAIL = "developer_stm@kwitech.com"
DEVELOPER_NOTIFICATION_EMAI = 'developer_nsp@kwitech.com'


#NSP DOC TYPE
NSP_DOCTYPE_BOS_DOCUMENT = "BOS DOCUMENT"
NSP_DOCTYPE_QOS_REVIEW = "QoS Review"
NSP_DOCTYPE_REFERENCE_DOCUMENT = "REFERENCE DOCUMENT"
NSP_DOCTYPE_SERVICE_ORDER = "SERVICE ORDER"
NSP_DOCTYPE_SIGNATURE = "SIGNATURE"
NSP_DOCTYPE_VIDEO_AUDIO = "Video/Audio"

#DATETIME FORMATS
ISO_DATE_FORMAT_STRING = 'YYYY-MM-DD'
ISO_DATETIME_FORMAT_STRING = 'YYYY-MM-DD HH:MM:SS'

# APP CONFIG
APP_NAME = "Service Quick"
APP_VERSION = "1.17.0"
APP_UPDATED = "2016-12-06"


# NSP CLIENT APP ID (to get the location of technician's device)
NSP_AGENT_APP_ID = "com.kwitech.android.nsp.agent"
SQ_AGENT_APP_ID = "com.kwitech.android.sqagent"

# LIST
DEFAULT_PAGE_SIZE = 25
DEFAULT_PAGE_INDICATOR_SIZE = 10

# AWS S3 credentials
AWSS3_ACCESS_KEY = config('AWSS3_ACCESS_KEY', cast=str)
AWSS3_SECRET_KEY = config('AWSS3_SECRET_KEY', cast=str)
AWSS3_BUCKET = config('AWSS3_BUCKET', cast=str)

# AZURE AD
CLIENT_ID = config('client_id', cast=str)
CLIENT_SECRET = config('client_secret', cast=str)
TENANT_ID = config('tenant_id', cast=str)
APP_SECRET = config('app_secret', cast=str)


# NSP BATCH
DEV_DOMAIN = "https://test.servicebench.com"
PRO_DOMAIN = "https://www.servicebench.com"